	@Test
	public void testV2LsRefsUnrecognizedArgument() throws Exception {
		PackProtocolException e = assertThrows(PackProtocolException.class,
				() -> uploadPackV2("command=ls-refs\n",
						PacketLineIn.delimiter(), "invalid-argument\n",
						PacketLineIn.end()));
		assertThat(e.getMessage(),
				containsString("unexpected invalid-argument"));
	}

